In [8]:
import pandas as pd
df = pd.read_csv("C:/Users/tolud/Desktop/PAU STUFF/Second semester note/COS102/diabetes.csv")
print (df)
df.head(5)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0      NaN  33.6
1              1     85.0           66.0           29.0      NaN  26.6
2              8    183.0           64.0            NaN      NaN  23.3
3              1     89.0           66.0           23.0     94.0  28.1
4              0    137.0           40.0           35.0    168.0  43.1
..           ...      ...            ...            ...      ...   ...
763           10    101.0           76.0           48.0    180.0  32.9
764            2    122.0           70.0           27.0      NaN  36.8
765            5    121.0           72.0           23.0    112.0  26.2
766            1    126.0           60.0            NaN      NaN  30.1
767            1     93.0           70.0           31.0      NaN  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/tolud/Desktop/PAU STUFF/Second semester note/COS102/diabetes.csv")
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   763 non-null    float64
 2   BloodPressure             733 non-null    float64
 3   SkinThickness             541 non-null    float64
 4   Insulin                   394 non-null    float64
 5   BMI                       757 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

(768, 9)

In [15]:
#no. of null values per column
df.isna().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [5]:
to_fill = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for col in to_fill:
    df[col] = df[col].fillna(df[col].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50,1
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31,0
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32,1
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.00000,180.000000,32.9,0.171,63,0
764,2,122.0,70.0,27.00000,155.548223,36.8,0.340,27,0
765,5,121.0,72.0,23.00000,112.000000,26.2,0.245,30,0
766,1,126.0,60.0,29.15342,155.548223,30.1,0.349,47,1
767,1,93.0,70.0,31.00000,155.548223,30.4,0.315,23,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [1]:
import pandas as pd
info = ['CSC','102','is','a','course']
df = pd.DataFrame(info)
print(df)

        0
0     CSC
1     102
2      is
3       a
4  course

In [12]:
# Define a dictionary containing employee data
data = {'Name':['Clem', 'Prince', 'Edward', 'Adele'],
        'Age':[27, 24, 22, 32],
        'Address':['Abuja', 'Kano', 'Minna', 'Lagos'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
 
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
df

     Name  Age Address Qualification
0    Clem   27   Abuja           Msc
1  Prince   24    Kano            MA
2  Edward   22   Minna           MCA
3   Adele   32   Lagos           Phd

In [14]:
df.iloc[2,1]

np.int64(22)

In [18]:
# iterating over rows using iterrows() function 
for Age, Address in df.iterrows():
    print(Age)
    print(Address)

0
Name              Clem
Age                 27
Address          Abuja
Qualification      Msc
Name: 0, dtype: object
1
Name             Prince
Age                  24
Address            Kano
Qualification        MA
Name: 1, dtype: object
2
Name             Edward
Age                  22
Address           Minna
Qualification       MCA
Name: 2, dtype: object
3
Name             Adele
Age                 32
Address          Lagos
Qualification      Phd
Name: 3, dtype: object

In [19]:
print(df.columns)
for col in df.columns:
 
    # printing the third element of the column
    print (df[col][3])

Index(['Name', 'Age', 'Address', 'Qualification'], dtype='object')
Adele
32
Lagos
Phd

In [20]:
# dictionary of lists
record = {'name':["Abel", "Kamsi", "Oyode", "Chinelo"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80,98]}
  
# creating a dataframe from a dictionary 
df = pd.DataFrame(record)


# saving the dataframe
df.to_csv('record.csv')